version: "3"

services:
  ubuntu-desktop:
    build: .
    ports:
      - "6080:80"
    environment:
      - VNC_RESOLUTION=1280x720
      - VNC_PASSWORD=${SERVICE_PASSWORD_VNC}
    restart: unless-stopped
