version: "3"

services:
  ubuntu-desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc:latest
    exposes:
      - "6080"
    environment:
      - VNC_PASSWORD=${SERVICE_PASSWORD_VNC}
      - RESOLUTION=1920x1080
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
