version: "3.8"

services:
  xrdp:
    build: .
    ports:
      - "3389:3389"
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole-mysql
      MYSQL_DATABASE: ${SERVICE_FQDN_GUACAMOLE:-guacamole_db}
      MYSQL_USER: ${SERVICE_USER_GUACAMOLE}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_GUACAMOLE}
    depends_on:
      - guacd
      - guacamole-mysql
    restart: unless-stopped

  guacd:
    image: guacamole/guacd
    restart: unless-stopped

  guacamole-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_MYSQL_ROOT}
      MYSQL_DATABASE: ${SERVICE_FQDN_GUACAMOLE:-guacamole_db}
      MYSQL_USER: ${SERVICE_USER_GUACAMOLE}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_GUACAMOLE}
    volumes:
      - guacamole-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  guacamole-mysql-data:
